# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SingPortoSeguro' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SingPortoSeguro
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'


  target 'SingPortoSeguroTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SingPortoSeguroUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
